### ISSUE TITLE
天気API

### ISSUE THREAD

**Issue by joryulife** [joryulife/TenkiOnAir#2]
APIから情報取得

**Comment by mori-ryoga** [comment]
[Weather API公式サイト](https://openweathermap.org/api)にアクセス

> サインアップ

> API KEYを取得後、ファイル内の変数を変更する。
`API_KEY = "xxxxxxxxxxxxxxxxxxx"`

> レスポンスはJSON形式で3時間ごとに5日分取得される

**残りのタスク**
- [1] Jsonデータから天気、温度などを抽出する。
